@extends('layout.app')

@section('title', 'Stock Inventory')

@section('content')

    <div class="animate-fade" style="max-width: 1200px; margin: 0 auto;">

        <div class="page-header no-print">
            <div>
                <h1 class="page-title">Inventory Management</h1>
                <p style="color: var(--text-muted); font-size: 0.9rem; margin-top: 5px;">Real-time stock levels and valuation.</p>
            </div>
            <div>
                <button onclick="window.print()" class="btn-print">
                    <svg width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>
                    Print Report
                </button>
            </div>
        </div>

        <div class="print-header">
            <div class="print-logo">NEXUS POS</div>
            <div class="print-doc-title">Inventory Status Report</div>
            <div class="print-meta">
                Date: {{ date('F d, Y') }} <br>
                Generated By: Admin
            </div>
        </div>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-icon purple">
                    <svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                </div>
                <div>
                    <div class="stat-label">Total Cost Value</div>
                    <div class="stat-value text-primary">
                        ${{ number_format(\App\Models\Product::sum(\Illuminate\Support\Facades\DB::raw('cost_price * qty')), 2) }}
                    </div>
                </div>
            </div>

            <div class="stat-card">
                <div class="stat-icon green">
                    <svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path></svg>
                </div>
                <div>
                    <div class="stat-label">Potential Revenue</div>
                    <div class="stat-value text-success">
                        ${{ number_format(\App\Models\Product::sum(\Illuminate\Support\Facades\DB::raw('sale_price * qty')), 2) }}
                    </div>
                </div>
            </div>

            <div class="stat-card">
                <div class="stat-icon red">
                    <svg width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                </div>
                <div>
                    <div class="stat-label">Low Stock Items</div>
                    <div class="stat-value text-danger">
                        {{ \App\Models\Product::where('qty', '<=', 5)->count() }}
                    </div>
                </div>
            </div>
        </div>

        <div class="report-card">
            <div class="card-header no-print">
                <h3>Product List</h3>
                <div class="badge-count">Total: {{ \App\Models\Product::count() }}</div>
            </div>

            <table class="report-table">
                <thead>
                    <tr>
                        <th style="padding-left: 1.5rem;">Product</th>
                        <th>Category</th>
                        <th class="text-right">Cost</th>
                        <th class="text-right">Price</th>
                        <th class="no-print" style="width: 25%;">Stock Level</th>
                        <th class="text-right" style="padding-right: 1.5rem;">Qty</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(\App\Models\Product::orderBy('qty', 'asc')->get() as $product)
                        <tr>
                            <td style="padding-left: 1.5rem;">
                                <div class="prod-name">{{ $product->name }}</div>
                                <div class="prod-code">{{ $product->barcode }}</div>
                            </td>
                            <td>
                                <span class="cat-badge">{{ $product->category->name ?? '-' }}</span>
                            </td>
                            <td class="text-right">${{ number_format($product->cost_price, 2) }}</td>
                            <td class="text-right font-bold">${{ number_format($product->sale_price, 2) }}</td>
                            
                            <td class="no-print">
                                <div class="progress-bg">
                                    @php 
                                        $percent = min($product->qty, 100);
                                        $color = $product->qty <= 5 ? '#ef4444' : ($product->qty < 20 ? '#f59e0b' : '#10b981');
                                    @endphp
                                    <div class="progress-fill" style="width: {{ $percent }}%; background: {{ $color }};"></div>
                                </div>
                            </td>

                            <td class="text-right" style="padding-right: 1.5rem;">
                                @if($product->qty <= 5)
                                    <span class="qty-text critical">{{ $product->qty }}</span>
                                @elseif($product->qty < 20)
                                    <span class="qty-text low">{{ $product->qty }}</span>
                                @else
                                    <span class="qty-text good">{{ $product->qty }}</span>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <div class="print-footer">
            <p>End of Report</p>
        </div>

    </div>

    <style>
        /* --- SCREEN STYLES (Default) --- */
        .page-header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 2rem; }
        .page-title { font-size: 1.5rem; font-weight: 800; color: var(--text-main); margin: 0; }
        
        .btn-print { background: var(--text-main); color: white; border: none; padding: 10px 20px; border-radius: 8px; font-weight: 600; cursor: pointer; display: flex; align-items: center; gap: 8px; transition: 0.2s; }
        .btn-print:hover { background: var(--primary); transform: translateY(-1px); }

        .stats-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1.5rem; margin-bottom: 2rem; }
        .stat-card { background: white; padding: 1.5rem; border-radius: 12px; border: 1px solid var(--border); display: flex; align-items: center; gap: 1rem; box-shadow: var(--shadow-sm); }
        
        .stat-icon { width: 48px; height: 48px; border-radius: 10px; display: flex; align-items: center; justify-content: center; }
        .stat-icon.purple { background: #e0e7ff; color: #4338ca; }
        .stat-icon.green { background: #dcfce7; color: #15803d; }
        .stat-icon.red { background: #fee2e2; color: #991b1b; }

        .stat-label { font-size: 0.8rem; font-weight: 700; color: var(--text-muted); text-transform: uppercase; margin-bottom: 4px; }
        .stat-value { font-size: 1.5rem; font-weight: 800; line-height: 1; }
        
        .text-primary { color: var(--primary); }
        .text-success { color: #166534; }
        .text-danger { color: #991b1b; }

        .report-card { background: white; border: 1px solid var(--border); border-radius: 12px; overflow: hidden; box-shadow: var(--shadow-sm); }
        .card-header { padding: 1.2rem 1.5rem; border-bottom: 1px solid var(--border); display: flex; justify-content: space-between; align-items: center; background: #f8fafc; }
        .card-header h3 { margin: 0; font-size: 1rem; font-weight: 700; color: var(--text-main); }
        .badge-count { background: white; border: 1px solid var(--border); padding: 4px 10px; border-radius: 20px; font-size: 0.8rem; font-weight: 600; color: var(--text-muted); }

        .report-table { width: 100%; border-collapse: collapse; }
        .report-table th { text-align: left; padding: 1rem; background: #fcfcfc; font-size: 0.75rem; font-weight: 700; text-transform: uppercase; color: var(--text-muted); border-bottom: 1px solid var(--border); letter-spacing: 0.05em; }
        .report-table td { padding: 1rem; border-bottom: 1px solid var(--border); vertical-align: middle; font-size: 0.9rem; color: var(--text-main); }
        .report-table tr:last-child td { border-bottom: none; }

        .prod-name { font-weight: 600; color: var(--text-main); }
        .prod-code { font-size: 0.8rem; color: var(--text-muted); font-family: monospace; }
        .cat-badge { background: #f1f5f9; padding: 4px 8px; border-radius: 4px; font-size: 0.8rem; color: var(--text-muted); }
        
        .progress-bg { height: 6px; width: 100%; background: #f1f5f9; border-radius: 10px; overflow: hidden; }
        .progress-fill { height: 100%; border-radius: 10px; }

        .qty-text { font-weight: 700; }
        .qty-text.critical { color: #991b1b; }
        .qty-text.low { color: #92400e; }
        .qty-text.good { color: var(--text-main); }

        .text-right { text-align: right; }
        .font-bold { font-weight: 700; }

        .print-header, .print-footer { display: none; }

        /* --- PRINT MODE (Bulletproof) --- */
        @media print {
            /* 1. Reset Global Layout */
            body, html { 
                background: white !important; 
                margin: 0 !important; 
                padding: 0 !important; 
                height: auto !important; 
                overflow: visible !important;
                width: 100% !important;
            }

            /* 2. Hide Dashboard Elements */
            .sidebar, nav, header, .no-print, .btn, .btn-print, footer, .header-bar { 
                display: none !important; 
            }

            /* 3. Expand Report to Full Width */
            .main-content, .container, .page-content, .animate-fade {
                width: 100% !important;
                max-width: 100% !important;
                margin: 0 !important;
                padding: 0 !important;
                border: none !important;
                box-shadow: none !important;
                position: static !important;
            }

            /* 4. Show Print Header */
            .print-header { 
                display: block !important; 
                margin-bottom: 30px; 
                border-bottom: 2px solid #000; 
                padding-bottom: 20px; 
            }
            .print-logo { font-size: 24px; font-weight: 800; text-transform: uppercase; }
            .print-doc-title { font-size: 18px; margin-top: 5px; }
            .print-meta { font-size: 12px; color: #555; text-align: right; position: absolute; top: 0; right: 0; }

            /* 5. Adjust Card & Table for Print */
            .report-card { border: none !important; box-shadow: none !important; }
            .report-table th { background-color: #eee !important; color: black !important; border-bottom: 2px solid #000 !important; }
            .report-table td { border-bottom: 1px solid #ddd !important; color: black !important; }
            
            /* 6. Stats Grid Adjustment */
            .stats-grid { gap: 10px !important; margin-bottom: 20px !important; }
            .stat-card { border: 1px solid #ccc !important; padding: 10px !important; box-shadow: none !important; }

            /* 7. Footer */
            .print-footer { display: block !important; margin-top: 40px; text-align: center; font-size: 10px; color: #555; border-top: 1px solid #ddd; padding-top: 10px; }
        }
    </style>

@endsection